name: Publish Package to npmjs
on:
  push:
    tags:
      - '*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: yarn/action-setup@v2
      - run: yarn install
      - run: yarn compile
      - run: yarn format:check
      - run: yarn lint:check
      - run: yarn test
      - run: yarn build
      - run: yarn config set '//registry.npmjs.org/:_authToken' "${NODE_AUTH_TOKEN}"
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: yarn publish --no-git-checks --access=public
